const USER_ACTIVITY_ONLINE_WINDOW_SECONDS = 5 * 60;
const USER_ACTIVITY_PASSIVE_TOUCH_INTERVAL_SECONDS = 5 * 60;
const USER_ACTIVITY_HEARTBEAT_MIN_INTERVAL_SECONDS = 30;
const USER_ACTIVITY_HEARTBEAT_MAX_CREDIT_SECONDS = 120;

export {
  USER_ACTIVITY_HEARTBEAT_MAX_CREDIT_SECONDS,
  USER_ACTIVITY_HEARTBEAT_MIN_INTERVAL_SECONDS,
  USER_ACTIVITY_ONLINE_WINDOW_SECONDS,
  USER_ACTIVITY_PASSIVE_TOUCH_INTERVAL_SECONDS,
};
