const AUTH_MESSAGE_VERSION = 1;
const KEY_DERIVATION_VERSION = 1;
const BESEEN_AUTH_DOMAIN = 'beseen.app';
const KEY_DERIVATION_KDF = 'HKDF-SHA-256';
const KEY_DERIVATION_INPUT = 'SEP-53-SIGNATURE';
const KEY_DERIVATION_INPUT_ENCODING = 'base64';
const KEY_DERIVATION_SALT = 'beseen.app/key-derivation/v1';
const KEY_DERIVATION_SIGNING_INFO = 'beseen.app/ed25519-signing-key/v1';
const KEY_DERIVATION_ENCRYPTION_INFO = 'beseen.app/x25519-encryption-key/v1';
const KEY_DERIVATION_SEED_LENGTH_BYTES = 32;

const AUTH_CHALLENGE_PURPOSES = ['registration', 'login'] as const;
const STELLAR_NETWORKS = ['public', 'testnet'] as const;
const USER_KEY_STATUSES = ['active', 'revoked'] as const;

const AUTH_NONCE_PATTERN = /^[A-Za-z0-9_-]{43}$/;
const BASE64_PUBLIC_KEY_PATTERN = /^[A-Za-z0-9+/]{43}=$/;
const PUBLIC_KEY_LENGTH_BYTES = 32;
const SEP53_SIGNATURE_LENGTH_BYTES = 64;
const REGISTRATION_TOKEN_LENGTH_BYTES = 32;
const REFRESH_TOKEN_LENGTH_BYTES = 32;
const MAX_AUTH_CHALLENGE_ATTEMPTS = 5;

type AuthChallengePurpose = (typeof AUTH_CHALLENGE_PURPOSES)[number];
type StellarNetwork = (typeof STELLAR_NETWORKS)[number];
type UserKeyStatus = (typeof USER_KEY_STATUSES)[number];

export {
  AUTH_CHALLENGE_PURPOSES,
  AUTH_MESSAGE_VERSION,
  AUTH_NONCE_PATTERN,
  BASE64_PUBLIC_KEY_PATTERN,
  BESEEN_AUTH_DOMAIN,
  KEY_DERIVATION_VERSION,
  KEY_DERIVATION_ENCRYPTION_INFO,
  KEY_DERIVATION_INPUT,
  KEY_DERIVATION_INPUT_ENCODING,
  KEY_DERIVATION_KDF,
  KEY_DERIVATION_SALT,
  KEY_DERIVATION_SEED_LENGTH_BYTES,
  KEY_DERIVATION_SIGNING_INFO,
  MAX_AUTH_CHALLENGE_ATTEMPTS,
  PUBLIC_KEY_LENGTH_BYTES,
  REFRESH_TOKEN_LENGTH_BYTES,
  REGISTRATION_TOKEN_LENGTH_BYTES,
  SEP53_SIGNATURE_LENGTH_BYTES,
  STELLAR_NETWORKS,
  USER_KEY_STATUSES,
};
export type { AuthChallengePurpose, StellarNetwork, UserKeyStatus };
