const KEY_DERIVATION_VERSION = 1;
const KEY_DERIVATION_KDF = 'HKDF-SHA-256';
const KEY_DERIVATION_INPUT = 'RAW-64-BYTE-STELLAR-TRANSACTION-SIGNATURE';
const KEY_DERIVATION_INPUT_ENCODING = 'raw-bytes';
const KEY_DERIVATION_INPUT_LENGTH_BYTES = 64;
const KEY_DERIVATION_SALT = 'beseen.app/key-derivation/v1';
const KEY_DERIVATION_SIGNING_INFO = 'beseen.app/ed25519-signing-key/v1';
const KEY_DERIVATION_ENCRYPTION_INFO = 'beseen.app/x25519-encryption-key/v1';
const KEY_DERIVATION_SEED_LENGTH_BYTES = 32;
const KEY_DERIVATION_TRANSACTION_FEE_STROOPS = '100';
const KEY_DERIVATION_TRANSACTION_SEQUENCE = '0';
const KEY_DERIVATION_TRANSACTION_MIN_TIME = '0';
const KEY_DERIVATION_TRANSACTION_MAX_TIME = '0';
const KEY_DERIVATION_TRANSACTION_OPERATION = 'manageData';
const KEY_DERIVATION_TRANSACTION_DATA_NAME = 'beseen_kdf_v1';
const KEY_DERIVATION_TRANSACTION_DATA_VALUE = 'beseen.app/key-derivation/v1';
const LOGIN_PROOF_VERSION = 1;
const LOGIN_PROOF_MAX_AGE_SECONDS = 300;

const STELLAR_NETWORKS = ['public', 'testnet'] as const;
const USER_KEY_STATUSES = ['active', 'revoked'] as const;

const BASE64_PUBLIC_KEY_PATTERN = /^[A-Za-z0-9+/]{43}=$/;
const PUBLIC_KEY_LENGTH_BYTES = 32;
const REFRESH_TOKEN_LENGTH_BYTES = 32;

type StellarNetwork = (typeof STELLAR_NETWORKS)[number];
type UserKeyStatus = (typeof USER_KEY_STATUSES)[number];

export {
  BASE64_PUBLIC_KEY_PATTERN,
  KEY_DERIVATION_VERSION,
  KEY_DERIVATION_ENCRYPTION_INFO,
  KEY_DERIVATION_INPUT,
  KEY_DERIVATION_INPUT_ENCODING,
  KEY_DERIVATION_INPUT_LENGTH_BYTES,
  KEY_DERIVATION_KDF,
  KEY_DERIVATION_SALT,
  KEY_DERIVATION_SEED_LENGTH_BYTES,
  KEY_DERIVATION_SIGNING_INFO,
  KEY_DERIVATION_TRANSACTION_DATA_NAME,
  KEY_DERIVATION_TRANSACTION_DATA_VALUE,
  KEY_DERIVATION_TRANSACTION_FEE_STROOPS,
  KEY_DERIVATION_TRANSACTION_MAX_TIME,
  KEY_DERIVATION_TRANSACTION_MIN_TIME,
  KEY_DERIVATION_TRANSACTION_OPERATION,
  KEY_DERIVATION_TRANSACTION_SEQUENCE,
  LOGIN_PROOF_MAX_AGE_SECONDS,
  LOGIN_PROOF_VERSION,
  PUBLIC_KEY_LENGTH_BYTES,
  REFRESH_TOKEN_LENGTH_BYTES,
  STELLAR_NETWORKS,
  USER_KEY_STATUSES,
};
export type { StellarNetwork, UserKeyStatus };
