const AVATAR_WEBP_QUALITY = 82;
const AVATAR_OUTPUT_SIZE_PX = 512;
const AVATAR_OUTPUT_FORMAT = 'webp';
const AVATAR_MIN_INPUT_SIZE_PX = 128;
const AVATAR_MAX_INPUT_PIXELS = 16_777_216;
const AVATAR_ALLOWED_INPUT_FORMATS = ['jpeg', 'png', 'webp'] as const;

export {
  AVATAR_WEBP_QUALITY,
  AVATAR_OUTPUT_FORMAT,
  AVATAR_OUTPUT_SIZE_PX,
  AVATAR_MAX_INPUT_PIXELS,
  AVATAR_MIN_INPUT_SIZE_PX,
  AVATAR_ALLOWED_INPUT_FORMATS,
};
