const BROADCAST_ENCRYPTION_VERSION = 1;
const BROADCAST_CONTENT_ENCRYPTION_SUITE = 'XCHACHA20-POLY1305-IETF';
const BROADCAST_KEY_WRAP_SUITE = 'X25519-XSALSA20-POLY1305-SEALEDBOX';
const BROADCAST_SIGNATURE_VERSION = 1;
const BROADCAST_RECIPIENT_PAGE_DEFAULT_LIMIT = 100;
const BROADCAST_RECIPIENT_PAGE_MAX_LIMIT = 250;
const BROADCAST_KEY_BATCH_MAX_ITEMS = 250;
const BROADCAST_CONTENT_KEY_BYTES = 32;
const SEALED_BOX_OVERHEAD_BYTES = 48;
const BROADCAST_WRAPPED_KEY_BYTES = BROADCAST_CONTENT_KEY_BYTES + SEALED_BOX_OVERHEAD_BYTES;
const BROADCAST_CONTENT_NONCE_BYTES = 24;
const BROADCAST_AEAD_OVERHEAD_BYTES = 16;
const BROADCAST_MAX_PLAINTEXT_BYTES = 65_536;
const BROADCAST_MIN_CIPHERTEXT_BYTES = BROADCAST_AEAD_OVERHEAD_BYTES + 1;
const BROADCAST_MAX_CIPHERTEXT_BYTES =
  BROADCAST_MAX_PLAINTEXT_BYTES + BROADCAST_AEAD_OVERHEAD_BYTES;
const BROADCAST_FEED_DEFAULT_LIMIT = 20;
const BROADCAST_FEED_MAX_LIMIT = 50;
const BROADCAST_DRAFT_LIST_DEFAULT_LIMIT = 20;
const BROADCAST_DRAFT_LIST_MAX_LIMIT = 50;
const BROADCAST_STATUSES = ['draft', 'published', 'canceled'] as const;
const BROADCAST_AUDIENCE_TYPES = ['demo_all_users', 'token_holders'] as const;
const BROADCAST_ACCESS_MODES = ['demo', 'token'] as const;

type BroadcastStatus = (typeof BROADCAST_STATUSES)[number];
type BroadcastAudienceType = (typeof BROADCAST_AUDIENCE_TYPES)[number];
type BroadcastAccessMode = (typeof BROADCAST_ACCESS_MODES)[number];

export {
  BROADCAST_AUDIENCE_TYPES,
  BROADCAST_ACCESS_MODES,
  BROADCAST_CONTENT_NONCE_BYTES,
  BROADCAST_CONTENT_ENCRYPTION_SUITE,
  BROADCAST_DRAFT_LIST_DEFAULT_LIMIT,
  BROADCAST_DRAFT_LIST_MAX_LIMIT,
  BROADCAST_ENCRYPTION_VERSION,
  BROADCAST_FEED_DEFAULT_LIMIT,
  BROADCAST_FEED_MAX_LIMIT,
  BROADCAST_KEY_WRAP_SUITE,
  BROADCAST_KEY_BATCH_MAX_ITEMS,
  BROADCAST_MAX_CIPHERTEXT_BYTES,
  BROADCAST_MIN_CIPHERTEXT_BYTES,
  BROADCAST_RECIPIENT_PAGE_DEFAULT_LIMIT,
  BROADCAST_RECIPIENT_PAGE_MAX_LIMIT,
  BROADCAST_SIGNATURE_VERSION,
  BROADCAST_STATUSES,
  BROADCAST_WRAPPED_KEY_BYTES,
};
export type { BroadcastAccessMode, BroadcastAudienceType, BroadcastStatus };
