const BROADCAST_ENCRYPTION_VERSION = 1;
const BROADCAST_CONTENT_ENCRYPTION_SUITE = 'XCHACHA20-POLY1305-IETF';
const BROADCAST_KEY_WRAP_SUITE = 'X25519-XSALSA20-POLY1305-SEALEDBOX';
const BROADCAST_SIGNATURE_VERSION = 1;
const BROADCAST_RECIPIENT_PAGE_DEFAULT_LIMIT = 100;
const BROADCAST_RECIPIENT_PAGE_MAX_LIMIT = 250;
const BROADCAST_KEY_BATCH_MAX_ITEMS = 250;
const BROADCAST_CONTENT_KEY_BYTES = 32;
const SEALED_BOX_OVERHEAD_BYTES = 48;
const BROADCAST_WRAPPED_KEY_BYTES = BROADCAST_CONTENT_KEY_BYTES + SEALED_BOX_OVERHEAD_BYTES;
const BROADCAST_STATUSES = ['draft', 'published'] as const;
const BROADCAST_AUDIENCE_TYPES = ['all_active_users', 'token_holders'] as const;

type BroadcastStatus = (typeof BROADCAST_STATUSES)[number];
type BroadcastAudienceType = (typeof BROADCAST_AUDIENCE_TYPES)[number];

export {
  BROADCAST_AUDIENCE_TYPES,
  BROADCAST_CONTENT_ENCRYPTION_SUITE,
  BROADCAST_ENCRYPTION_VERSION,
  BROADCAST_KEY_WRAP_SUITE,
  BROADCAST_KEY_BATCH_MAX_ITEMS,
  BROADCAST_RECIPIENT_PAGE_DEFAULT_LIMIT,
  BROADCAST_RECIPIENT_PAGE_MAX_LIMIT,
  BROADCAST_SIGNATURE_VERSION,
  BROADCAST_STATUSES,
  BROADCAST_WRAPPED_KEY_BYTES,
};
export type { BroadcastAudienceType, BroadcastStatus };
