const DISCOVER_SCORE_VERSION = 3;
const DISCOVER_FOLLOWER_CAP = 1_000;
const DISCOVER_FOLLOWER_WEIGHT = 25;
const DISCOVER_ACCOUNT_AGE_WEIGHT = 5;
const DISCOVER_AVATAR_WEIGHT = 2;
const DISCOVER_RANKING_BATCH_SIZE = 500;
const DISCOVER_RECENT_FOLLOWER_CAP = 100;
const DISCOVER_ACTIVITY_WINDOW_DAYS = 30;
const DISCOVER_RECENCY_HALF_LIFE_DAYS = 7;
const DISCOVER_ACCOUNT_MATURITY_DAYS = 30;
const DISCOVER_RECENT_FOLLOWER_WEIGHT = 10;
const DISCOVER_CLAIMED_BOUNTY_COUNT_CAP = 50;
const DISCOVER_LAST_TOKEN_PURCHASE_WEIGHT = 7;
const DISCOVER_CLAIMED_USDC_AMOUNT_WEIGHT = 9;
const DISCOVER_RECIPROCAL_CHAT_COUNT_CAP = 30;
const DISCOVER_CLAIMED_BOUNTY_COUNT_WEIGHT = 6;
const DISCOVER_CLAIMED_USDC_AMOUNT_CAP = 1_000;
const DISCOVER_LAST_RECIPROCAL_CHAT_WEIGHT = 4.5;
const DISCOVER_PUBLISHED_BROADCAST_COUNT_CAP = 20;
const DISCOVER_RECIPROCAL_CHAT_COUNT_WEIGHT = 10.5;
const DISCOVER_LAST_PUBLISHED_BROADCAST_WEIGHT = 4;
const DISCOVER_PUBLISHED_BROADCAST_COUNT_WEIGHT = 7;
const DISCOVER_ACTIVE_SECONDS_30D_CAP = 36_000;
const DISCOVER_ACTIVE_SECONDS_30D_WEIGHT = 5;
const DISCOVER_ACTIVE_DAYS_30D_CAP = 15;
const DISCOVER_ACTIVE_DAYS_30D_WEIGHT = 3;
const DISCOVER_LAST_ACTIVE_WEIGHT = 2;
const DISCOVER_LAST_ACTIVE_HALF_LIFE_DAYS = 3;
const DISCOVER_RANKING_INTERVAL_MS = 30 * 60 * 1_000;

const DISCOVER_NEW_USER_BOOSTS = [
  { maximumAgeDays: 3, boost: 5 },
  { maximumAgeDays: 7, boost: 3 },
  { maximumAgeDays: 14, boost: 1 },
] as const;

const DISCOVER_BOUNTY_AMOUNT_ASSET_CODE = 'USDC';

export {
  DISCOVER_ACCOUNT_AGE_WEIGHT,
  DISCOVER_ACCOUNT_MATURITY_DAYS,
  DISCOVER_AVATAR_WEIGHT,
  DISCOVER_ACTIVITY_WINDOW_DAYS,
  DISCOVER_ACTIVE_DAYS_30D_CAP,
  DISCOVER_ACTIVE_DAYS_30D_WEIGHT,
  DISCOVER_ACTIVE_SECONDS_30D_CAP,
  DISCOVER_ACTIVE_SECONDS_30D_WEIGHT,
  DISCOVER_BOUNTY_AMOUNT_ASSET_CODE,
  DISCOVER_CLAIMED_BOUNTY_COUNT_CAP,
  DISCOVER_CLAIMED_BOUNTY_COUNT_WEIGHT,
  DISCOVER_CLAIMED_USDC_AMOUNT_CAP,
  DISCOVER_CLAIMED_USDC_AMOUNT_WEIGHT,
  DISCOVER_FOLLOWER_CAP,
  DISCOVER_FOLLOWER_WEIGHT,
  DISCOVER_LAST_PUBLISHED_BROADCAST_WEIGHT,
  DISCOVER_LAST_ACTIVE_HALF_LIFE_DAYS,
  DISCOVER_LAST_ACTIVE_WEIGHT,
  DISCOVER_LAST_RECIPROCAL_CHAT_WEIGHT,
  DISCOVER_LAST_TOKEN_PURCHASE_WEIGHT,
  DISCOVER_NEW_USER_BOOSTS,
  DISCOVER_PUBLISHED_BROADCAST_COUNT_CAP,
  DISCOVER_PUBLISHED_BROADCAST_COUNT_WEIGHT,
  DISCOVER_RANKING_BATCH_SIZE,
  DISCOVER_RANKING_INTERVAL_MS,
  DISCOVER_RECENCY_HALF_LIFE_DAYS,
  DISCOVER_RECENT_FOLLOWER_CAP,
  DISCOVER_RECENT_FOLLOWER_WEIGHT,
  DISCOVER_RECIPROCAL_CHAT_COUNT_CAP,
  DISCOVER_RECIPROCAL_CHAT_COUNT_WEIGHT,
  DISCOVER_SCORE_VERSION,
};
