const MESSENGER_INITIAL_SEQUENCE = 1;
const MESSENGER_CONVERSATION_LIST_DEFAULT_LIMIT = 20;
const MESSENGER_CONVERSATION_LIST_MAX_LIMIT = 50;

export {
  MESSENGER_CONVERSATION_LIST_DEFAULT_LIMIT,
  MESSENGER_CONVERSATION_LIST_MAX_LIMIT,
  MESSENGER_INITIAL_SEQUENCE,
};
