const MESSENGER_INITIAL_SEQUENCE = 1;
const MESSENGER_CONVERSATION_LIST_DEFAULT_LIMIT = 20;
const MESSENGER_CONVERSATION_LIST_MAX_LIMIT = 50;
const MESSENGER_MESSAGE_HISTORY_DEFAULT_LIMIT = 30;
const MESSENGER_MESSAGE_HISTORY_MAX_LIMIT = 100;
const MESSENGER_EMPTY_READ_SEQUENCE = 0;
const MESSENGER_ENCRYPTION_VERSION = 1;
const MESSENGER_SIGNATURE_VERSION = 1;
const MESSENGER_CONTENT_ENCRYPTION_SUITE = 'XCHACHA20-POLY1305-IETF';
const MESSENGER_KEY_WRAP_SUITE = 'X25519-XSALSA20-POLY1305-SEALEDBOX';
const MESSENGER_CONTENT_KEY_BYTES = 32;
const MESSENGER_SEALED_BOX_OVERHEAD_BYTES = 48;
const MESSENGER_WRAPPED_KEY_BYTES =
  MESSENGER_CONTENT_KEY_BYTES + MESSENGER_SEALED_BOX_OVERHEAD_BYTES;
const MESSENGER_CONTENT_NONCE_BYTES = 24;
const MESSENGER_AEAD_OVERHEAD_BYTES = 16;
const MESSENGER_MAX_PLAINTEXT_BYTES = 65_536;
const MESSENGER_MIN_CIPHERTEXT_BYTES = MESSENGER_AEAD_OVERHEAD_BYTES + 1;
const MESSENGER_MAX_CIPHERTEXT_BYTES =
  MESSENGER_MAX_PLAINTEXT_BYTES + MESSENGER_AEAD_OVERHEAD_BYTES;
const MESSENGER_BOUNTY_MIN_DURATION_SECONDS = 1;
const MESSENGER_BOUNTY_MAX_DURATION_SECONDS = 31_536_000;
const MESSENGER_BOUNTY_ASSET_CODE_PATTERN = /^[A-Z0-9]{1,12}$/;
const MESSENGER_BOUNTY_AMOUNT_PATTERN = /^(?:0|[1-9]\d{0,11})(?:\.\d{1,7})?$/;
const MESSENGER_BOUNTY_STATUSES = ['offered', 'claimable', 'claimed', 'expired'] as const;

type MessengerBountyStatus = (typeof MESSENGER_BOUNTY_STATUSES)[number];

export {
  MESSENGER_CONVERSATION_LIST_DEFAULT_LIMIT,
  MESSENGER_CONVERSATION_LIST_MAX_LIMIT,
  MESSENGER_BOUNTY_AMOUNT_PATTERN,
  MESSENGER_BOUNTY_ASSET_CODE_PATTERN,
  MESSENGER_BOUNTY_MAX_DURATION_SECONDS,
  MESSENGER_BOUNTY_MIN_DURATION_SECONDS,
  MESSENGER_BOUNTY_STATUSES,
  MESSENGER_CONTENT_ENCRYPTION_SUITE,
  MESSENGER_CONTENT_NONCE_BYTES,
  MESSENGER_EMPTY_READ_SEQUENCE,
  MESSENGER_ENCRYPTION_VERSION,
  MESSENGER_INITIAL_SEQUENCE,
  MESSENGER_KEY_WRAP_SUITE,
  MESSENGER_MAX_CIPHERTEXT_BYTES,
  MESSENGER_MESSAGE_HISTORY_DEFAULT_LIMIT,
  MESSENGER_MESSAGE_HISTORY_MAX_LIMIT,
  MESSENGER_MIN_CIPHERTEXT_BYTES,
  MESSENGER_SIGNATURE_VERSION,
  MESSENGER_WRAPPED_KEY_BYTES,
};
export type { MessengerBountyStatus };
