const MAX_CREATOR_CATEGORIES = 5;
const MAX_CREATOR_CATEGORY_LENGTH = 32;
const MAX_CREATOR_SKILLS = 20;
const MAX_CREATOR_SKILL_LENGTH = 50;

export {
  MAX_CREATOR_CATEGORIES,
  MAX_CREATOR_CATEGORY_LENGTH,
  MAX_CREATOR_SKILLS,
  MAX_CREATOR_SKILL_LENGTH,
};
